### PR TITLE
monkeypatch throws recursion depth error on super() constructor

### PR DESCRIPTION
**Pull request by psipeter**
I'm probably just missing something simple here with the monkeypatch approach (I've never done modifications this way before). I modeled it off the links @arvoelke put in the googledoc, but I keep getting maximum recursion depth exceeded errors when I call the super() constructor.

### CODE REVIEW

**Comment by arvoelke** [comment]
The problem is likely that you are patching it more than once. The second time you patch it you import your patched version and set it up to subclass itself.

Because you are doing things in a notebook this trap is very easy (e.g., from running the cell twice). I would start putting things into their own files, and apply the patch in the library's `__init__.py`.

**Comment by psipeter** [comment]
OK, I separated the files and did some basic library setup. Now I'm running into another error when I run test_feedforward.py. Here's the traceback:

```
Building finished in 0:00:01.                                                   
Simulating finished in 0:00:01.                                                 
Traceback (most recent call last):
  File "test_feedforward.py", line 117, in <module>
    decoders_bio, plots)
  File "test_feedforward.py", line 52, in feedforward
    sim.run(t_final)
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/simulator.py", line 275, in run
    self.run_steps(steps, progress_bar=progress_bar)
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/simulator.py", line 297, in run_steps
    self.step()
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/simulator.py", line 308, in step
    step_fn()
  File "/home/pduggins/.virtualenvs/oracle/local/lib/python2.7/site-packages/nengo/builder/neurons.py", line 68, in step_simneurons
    self.neurons.step_math(dt, J, output, *states)
TypeError: step_math() takes exactly 6 arguments (4 given)
```

**Comment by arvoelke** [comment]
What happened to 

```
@Builder.register(BahlNeuron)
def build_bahlneuron(model,neuron_type,ens):
    ...
```
?

Also FYI to activate the monkeypatch you need to import your library (place `import bioneuron_oracle` at the top). `__init__.py` is called when any import of the form `bioneuron_oracle.*` is executed.

You should also make all imports absolute (e.g., instead of `import foobar` you should `import bioneuron_oracle` and then access `bioneuron_oracle.foobar` _or_ `import bioneuron_oracle.foobar`) in order to ensure that `__init__.py` is always being executed. You can refer to `nengo` or `nengolib` to see the conventions for importing from within the library and from within unit tests.

**Comment by psipeter** [comment]
Yep, I needed to `import bioneuron_oracle` in monkeypatch.py.

`build_bioneuron()`  is still in `builder.py`

**Comment by arvoelke** [comment]
See https://github.com/nengo/nengo/blob/84db35b5dd673ec715c4b11a0a9afae074f1895f/nengo/utils/tests/test_connection.py#L39 for an example of how to use the `plt` test fixture to produce subplots.

**Pull request closed without merging**
